services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Verilerin Jenkins her çalıştığında silinmemesi için eklendi

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: .
    ports:
      - "5000:9000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/loomixDB
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=loomix_super_gizli_anahtar_123 # Güvenlik anahtarı hatasını çözen satır
    depends_on:
      - mongodb
      - redis
      - rabbitmq

volumes:
  mongo_data: # Kalıcı veritabanı alanı